
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: jobs.crane.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.provider
    name: PROVIDER
    type: string
  - JSONPath: .spec.repo
    name: REPO
    type: string
  group: crane.crossplane.io
  names:
    kind: Job
    plural: jobs
  scope: Cluster
  subresources: {}
  validation:
    openAPIV3Schema:
      description: A Job configures a crane Job.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: A JobSpec defines the desired state of a Job.
          properties:
            provider:
              type: string
            repo:
              type: string
          required:
          - provider
          - repo
          type: object
      required:
      - spec
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
